version: "3"
services:
  nginx:
    image: nginx
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - 80:80
    volumes:
      - ${PWD}/swarm/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - overlay
  jupyterhubserver:
    image: cloudxlabs/jupyterhub
    ports:
      - 8000:8000
      - 8081:8081
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/swarm/env:/srv/jupyterhub/env
    networks:
      - overlay

networks:
  overlay:
    driver: overlay

